# Generated by Django 3.0.7 on 2020-06-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='features',
            new_name='featured',
        ),
    ]
