# Generated by Django 3.0.7 on 2020-06-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200620_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nect_post',
            new_name='next_post',
        ),
    ]
